contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dcmtest channel"
    url: https://nfcore.slack.com/channels/dcmtest
    about: Discussion about the nf-core/dcmtest pipeline
